Use add_css_file to add custom CSS
`add_stylesheet` was deprecated in Sphinx 1.8.0b1 (sphinx-doc/sphinx#4815).
This fixes the following error when building docs with sphinx 4.1.1:

    running build_sphinx
    Running Sphinx v4.1.1
    making output directory... done
    
    Exception occurred:
      File "/home/sean/software/dh-virtualenv/src/dh-virtualenv-1.2.2/doc/conf.py", line 30, in setup
        app.add_stylesheet('css/custom.css')
    AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
    The full traceback has been saved in /tmp/sphinx-err-f3yvk765.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!